# Generated by Django 4.0.6 on 2022-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('salary', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField()),
                ('office', models.CharField(blank=True, default='', max_length=100)),
                ('extn', models.IntegerField(blank=True, default='0')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
